### ISSUE TITLE
Export of chain of six different mononers to HELM is wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2075] opened 2024-07-03 16:43 UTC
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load from file: [Export of chain of six different mononers to HELM is wrong.zip](https://github.com/user-attachments/files/16087995/Export.of.chain.of.six.different.mononers.to.HELM.is.wrong.zip)
![image](https://github.com/epam/Indigo/assets/26869421/74a8bb46-d54f-4376-a31e-90d23cbed52e)
3. Save canvas to HELM

**Actual behavior**
Export result contains wrong chains: `RNA1{R(A)}|PEPTIDE1{A}|CHEM1{[SMCC]}|RNA2{R(A)P}|PEPTIDE2{C}|CHEM2{[A6OH]}$RNA1,PEPTIDE1,1:R2-1:R1PEPTIDE1,CHEM1,1:R2-1:R1CHEM1,RNA2,1:R2-1:R1RNA2,PEPTIDE2,3:R2-3:R1PEPTIDE2,CHEM2,1:R2-1:R1$$$V2.0`
![image](https://github.com/epam/Indigo/assets/26869421/97cab309-7aa2-4968-9d34-d1fcaec7f126)

**Expected behavior**
Export result is correct: `RNA1{R(A)}|PEPTIDE1{A}|CHEM1{[SMPEG2]}|RNA2{R(A)P}|PEPTIDE2{C}|CHEM2{[A6OH]}$RNA1,PEPTIDE1,1:R2-1:R1|PEPTIDE1,CHEM1,1:R2-1:R1|CHEM1,RNA2,1:R2-1:R1|RNA2,PEPTIDE2,3:R2-1:R1|PEPTIDE2,CHEM2,1:R2-1:R1$$$V2.0`
![image](https://github.com/epam/Indigo/assets/26869421/c71b4fdd-1f7c-4637-aae3-eeaed6008af8)

**Versions**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
- Indigo Toolkit Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/Indigo/issues/1188

**Comment by AliaksandrDziarkach** [comment] 2024-07-04 10:25
This is duplicate of #2067

**Closed by AliaksandrDziarkach** 2024-07-04 10:25 UTC
Labels: Bug, Priority: High, HELM

**Comment by AlexeyGirin** [comment] 2024-07-12 07:25
Fixed.
![image](https://github.com/user-attachments/assets/78a73979-75a2-45ce-bb3f-5f4c3a35404d)

- Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
- Indigo Toolkit Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)
