### ISSUE TITLE
System loads HELM even if connection point data is wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2186] opened 2024-08-06 10:27 UTC
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type: `CHEM1{[A6OH]}|PEPTIDE1{A}$CHEM1,PEPTIDE1,1:R4-1:R1$$$V2.0`
![image](https://github.com/user-attachments/assets/09ade97c-577d-4038-ae6f-f7620df0d075)

**Actual behavior**
Loads chain without error
![image](https://github.com/user-attachments/assets/3030c1f4-3035-4768-9c3d-9b796fe6d4e2)

**Expected behavior**
Error should occur since  A6OH CHEM doesn't have R4 connection point

**Versions**
- Ketcher Version 2.23.0-rc.3 Build at 2024-08-01; 05:31:23
- Indigo Toolkit Version Version 1.23.0-dev.3.2-gb9ac1d93-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/Indigo/issues/1188

**Comment by AlexeyGirin** [comment] 2024-08-26 13:27
Fixed but on review

**Comment by AliaksandrDziarkach** [comment] 2024-08-29 17:32
duplicate of #2066

**Closed by AliaksandrDziarkach** 2024-08-29 17:32 UTC
Labels: Bug, Priority: Medium, HELM
