### ISSUE TITLE
About .net core

### ISSUE THREAD

**Issue by AlexRen01** [epam/Indigo#140] opened 2019-07-24 08:31 UTC
Hello, dear author:

Thanks to the support of indigo, I have great convenience in dealing with compounds in my work. However, due to the upgrade of working environment, I have to use. net core to develop structured processing. Is it possible to upgrade Indigo to. net core in the near future?

Thank you!

**Comment by mkviatkovskii** [comment] 2019-10-22 13:57
Dear @AlexRen01,
Thank you for your question. Yes, we have plans to create Indigo package for lowest possible version of .NET standard. I'll notify you when it is ready.

**Comment by pshenichnov** [comment] 2019-10-29 13:00
hi @mkviatkovskii, do you have any estimation when we should expect .Net Core version? :)

we are interested in it as well

**Comment by mkviatkovskii** [comment] 2019-11-06 10:09
Dear @pshenichnov,
At the moment I am experimenting with porting Indigo native functions calling to .NET Core (and maybe even .NET Standard). Hope to provide an experimental version soon, so stay tuned.

**Comment by xjjius** [comment] 2019-12-25 05:37
Dear @mkviatkovskii 
Is the NET Standard version ready? Can I get it from NuGet now?

**Comment by pshenichnov** [comment] 2020-03-31 13:57
Hi guys, do you have any update on .NET Core version? Would be good if you could provide any estimations.

**Comment by mkviatkovskii** [comment] 2020-04-04 07:59
Hi @pshenichnov, @xjjius could you please clarify what target version of .NET Core is preferred for you? As far as I see, the minimal supported version is .NET Core 2.0, should I create the packages for it, or for .NET Core 2.1 LTS? Or maybe for both of them, and some newer versions too? 
It's not totally clear for me if there is some inter-version compatibility between .NET Core version.

At this point this is the only thing that stops us from releasing the .NET Core package.

Thank you in advance.

**Comment by xjjius** [comment] 2020-04-04 10:47
Dear @mkviatkovskii
Thank you for your reply. As far as I know, the NET standard 2.0+ version would be a good choice because both NET Framework (Windows) and NET Core (cross-platform) projects, as well as projects not involving web applications can use it. but I am not sure if it is possible to only use NET Standard 2.0+ APIs to implement Indigo.NET.

Speaking of NET core, Microsoft has released the NET Core 3.1 version (built on NET Standard 2.1). If you are only mean to support the new cross-platform NET core projects, I would say the newer version the better.

Thanks again for developing and maintaining this wonderful open source project for cheminformatics.

**Comment by yeskela** [comment] 2020-04-04 12:33
hi @mkviatkovskii, agreed with @xjjius, the NET standard 2.0+ version would be a good choice. Thanks much!

**Comment by mkviatkovskii** [comment] 2020-04-04 15:42
Dear @xjjius and @yeskela! Thank you very much for the feedback!

I definitely agree, targeting .NET Standard 2.0 looks like being the best solution. The problem is that we currently use `System.Reflection.Emit.ModuleBuilder` for loading native libraries, and this class is supported only by .NET Standard 2.1. I believe it is possible to avoid using it, but is requires a plenty of work. And I hope to release a .NET Core release as soon as possible.

So right now I'm able to use some multi-targeting, something like: "netstandard2.1;netcoreapp2.1;net46". The main question is, does it suit your (and other users) current needs?

**Comment by yeskela** [comment] 2020-04-05 01:55
hi @mkviatkovskii, NET Standard 2.1 will perfectly work for our project. Thanks much and appreciate!

**Comment by xjjius** [comment] 2020-04-05 02:21
Hi  @mkviatkovskii, NET Standard 2.1 suits my project perfectly. Thank you so much for your diligent work.

**Comment by pshenichnov** [comment] 2020-04-14 13:19
hi, @mkviatkovskii. Do you have any plans to update Nuget with the changes any time soon?

**Comment by mkviatkovskii** [comment] 2020-04-16 10:39
Hi, @pshenichnov. The package is ready. I just want to test it a little bit more, since the wrapper is heavily remodeled. But I have suddenly faced some issues, since we use IronPython for testing wrappers, and IronPython support for .NET Core is way imperfect.

I may upload an unstable version of package and maybe get some feedback from you.

**Comment by xjjius** [comment] 2020-04-17 02:35
Hi, @mkviatkovskii Thank you for your work. Please upload the unstable version whenever you feel OK. I can test it. One of my projects which extensively used the Indigo.NET lib is written in C#. I can also test it on Linux.

**Comment by mkviatkovskii** [comment] 2020-04-20 01:06
Hi @xjjius, @pshenichnov, @yeskela, @AlexRen01.

Preliminary version of new Indigo API targeting .NET Standard 2.0 is ready and could be downloaded [here](https://www.nuget.org/packages/Indigo.Net/1.4.0-beta.12).

Major differences:
* All Indigo APIs are merged into single .NET assembly. This seems to be required for correct interaction between Indigo core API and plugins.
* Using P/Invoke for calling native functions instead of AssemblyBuilder. Overhead of interoperability between managed and unmanaged code should be significally decreased.
* nupkg structure updated to .NET Core structure, native libraries are placed in the same folder as Indigo.Net.dll. According to my tests, this should fix issues with dynamically loading native libraries.
* Support for 32-bit versions of .NET runtimes dropped. This could be temporary decision, so please let me know if you really need 32-bit version of Indigo.Net.

Thank you for your patience. Please let me know if you have any problems with this package, any feedback is very appreciated.

**Comment by xjjius** [comment] 2020-04-20 12:09
Dear @mkviatkovskii. Thank you for your update. I have downloaded and run some test code. The basic functionality seems fine for me. However I got bunch of MSB3246 warning message during building process: 

Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3246: Resolved file has a bad
 image, no metadata, or is otherwise inaccessible. Assembly file '/root/.nuget/packages/indigo.net/1.4.0-beta.12/lib/ne
tstandard2.0/indigo-renderer.dll' could not be opened -- PE image doesn't contain managed metadata.

This warning message showed up for all native libs such as: bingo.dll, indigo.dll. indigo-renderer.dll, indigo-inchi.dll etc..

But this won't affect the program though, they can still successfully run and give the correct result.

Another issue is, when I was trying to run it under linux (Ubantu 18.04) with NET CORE SDK 3.1 installed. I got this:
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'indigo' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libindigo: cannot open shared object file: No such file or directory

It is obvious that the linux version of the native libs such as libindigo.so, libindigo-renderer.so, libindigo-inchi.so, etc. were not automatically installed on linux so that the P/Invoke can not find them. I will try manully build and install the native libs on linux and see if it works.

**Comment by mkviatkovskii** [comment] 2020-04-20 12:34
Dear @xjjius,
Yes, these DLLs are native and do not contain any managed data. Maybe MSBuild does not like that they are located in the same folder as managed libraries.

As for Linux, this is strange: I have also attached native libraries for Linux amd64 and macOS. You can unzip nupkg and find *.so and *.dylib also in lib/netstandard2.0 folder. 
I have checked Linux .NET Core via IronPython, and it worked fine. Maybe IronPython uses non-standard methods for loading assemblies (like settings some special LD_LIBRARY_PATH).
Could you please let me know, how do you run Indigo.Net on Linux? I’ll reproduce it on my machine.

**Comment by xjjius** [comment] 2020-04-20 13:17
Dear @mkviatkovskii 
This is how I run my test code on Linux.
I just copy the whole solution folder (Test/) to /usr/local/src. Then cd to the fold where the Test.csproj (./Test/Test/) file located. And then
`dotnet run Test`
This will build and run the project. I also tried someting like 
`dotnet ./bin/Debug/netcoreapp3.1/Test.dll`
which only run built Dlls.
Both of them gave me the same

**Comment by xjjius** [comment] 2020-04-20 13:21
Dear @mkviatkovskii
Thanks again for your reply. I tried add the native lib path to LD_LIBRARY_PATH, and it worked now!

**Comment by mkviatkovskii** [comment] 2020-04-20 13:29
Dear @xjjius, 
I tried to create a simple .NET Core console application following this steps:
```bash
mkdir IndigoNupkgTest
cd IndigoNupkgTest
dotnet new console
dotnet add package Indigo.Net --version 1.4.0-beta.12
```
Then I wrote following code to Program.cs:
```csharp
﻿using System;
using com.epam.indigo;

namespace IndigoNupkgTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var i = new Indigo();
            var ii = new IndigoInchi(i);
            Console.WriteLine(i.version());
            Console.WriteLine(ii.getInchi(i.loadMolecule("C")));
        }
    }
}
```
And the again in Bash:
```
$ dotnet run
# ... warnings MSB3246
1.4.0-beta.12-g12ec19ed linux64
InChI=1S/CH4/h1H4
```
As far as I understand, Nuget package was installed to `~/.nuget/packages/indigo.net/1.4.0-beta.12` and so all native libraries could be found in `~/.nuget/packages/indigo.net/1.4.0-beta.12/lib/netstandard2.0/`:
```bash
$ ls ~/.nuget/packages/indigo.net/1.4.0-beta.12/lib/netstandard2.0/
Indigo.Net.dll  indigo-inchi.dll     libbingo.dylib         libindigo-inchi.so        libindigo.dylib  vcruntime140.dll
bingo.dll       indigo-renderer.dll  libbingo.so            libindigo-renderer.dylib  libindigo.so     vcruntime140_1.dll
concrt140.dll   indigo.dll           libindigo-inchi.dylib  libindigo-renderer.so     msvcp140.dll
```
Could you please take a look, are there any native libraries in this folder on your machine?

**Comment by xjjius** [comment] 2020-04-20 13:39
Dear @mkviatkovskii
Thank you for your help. I think the problem of mine maybe the $LD_LIBRARY_PATH env. I had set this env for my other project. The runtime will find the native libs from here first. For some reason, it will not find the ~/.nuget/packages/indigo.net/1.4.0-beta.12/lib/netstandard2.0/ path. So I add this path to $LD_LIBRARY_PATH and it worked. Thanks again for your help.

**Comment by mkviatkovskii** [comment] 2020-04-22 11:33
OK, I am closing this issue for now. Please fill free to reopen it or comment if you have any problems.

**Closed by mkviatkovskii** 2020-04-22 11:33 UTC
Labels: Indigo API, enhancement

**Comment by trommlbomml** [comment] 2021-07-20 10:45
Is it much effort to support 32-bit builds? I have a 32-Bit WPF application where switching may be too hard as I have other 32-bit dependencies as well. I would like to switch to the newer version, because the current version 1.2.4 produces stackoverflows for certain molfiles and a newer version fixed this properly.

**Comment by mkviatkovskii** [comment] 2021-07-21 10:30
Dear @trommlbomml,
No, with latest version of Indigo it's not a big deal to support 32-bit builds as well. We plan to restore 32-bit compatibility in newest release, please stay tuned, it's should be released very soon.

**Comment by rbri** [comment] 2021-07-21 11:08
@mkviatkovskii a version fresh 32 bit version will be great, and if we can have it soon it will be even greater!
