### ISSUE TITLE
Multi-Tailed Arrows are displayed faded when saved to SVG/PNG

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#2536] opened 2024-10-08 14:11 UTC
**Summary**
Multi-Tailed Arrows are displayed faded when saved to SVG/PNG

**Steps to Reproduce**
1. Add Multi-Tailed Arrows on canvas
2. Save as SVG and PNG
3. Look at saving preview

**Actual behavior**
Multi-Tailed Arrows are displayed faded when saved to SVG/PNG in preview but looks normal in saved file

**Expected behavior**
Multi-Tailed Arrows are displayed as on canvas when saved to SVG/PNG in preview window

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.1]
**Indigo version** 
[Version 1.25.0-rc.1]

**Attachments**
![2024-10-08_17h08_36](https://github.com/user-attachments/assets/5b2764ef-8826-4934-be84-8c28c17cd189)
![2024-10-08_17h08_41](https://github.com/user-attachments/assets/32ba5f8b-a37e-4fd1-961d-d1e60e5363d9)
Closer look
![2024-10-08_17h10_25](https://github.com/user-attachments/assets/61ba54b1-5b24-4291-be9e-30ee0c1becaf)

**Additional context**
Bug found when testing: https://github.com/epam/Indigo/issues/2400
May be related to: https://github.com/epam/Indigo/issues/2175

**Comment by AliaksandrDziarkach** [comment] 2024-10-09 10:26
Looks like this is duplicate of #2447

**Closed by AliaksandrDziarkach** 2024-10-09 10:26 UTC
Labels: Bug, Priority: Low, SVG/PNG, Cascade reactions

**Comment by Zhirnoff** [comment] 2024-10-15 13:00
Tested. Bug fixed.

![2024-10-15_15h57_43](https://github.com/user-attachments/assets/6729d05e-b255-4b8d-b710-407b8e53f058)
![2024-10-15_15h57_48](https://github.com/user-attachments/assets/c63c8006-3b38-4fc3-92cd-d1d3564d312a)
![2024-10-15_15h58_06](https://github.com/user-attachments/assets/0a77e77b-43a4-4474-b3ed-5f74d93b0f94)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.2]
**Indigo version** 
[Version 1.25.0-rc.2]
