### ISSUE TITLE
HELM loader ignores range token

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2063] opened 2024-07-03 08:40 UTC
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type: `RNA1{[Sm5moe]([m2nprn])[mepo2]'3-7'}$$$$V2.0`
![image](https://github.com/epam/Indigo/assets/26869421/e63433aa-3ea7-4202-bbf1-f8363e991985)

**Actual behavior**
Loads RNA (but without range)
![image](https://github.com/epam/Indigo/assets/26869421/a6a09f9c-71c1-4d7a-8251-70fc0dc365cb)

**Expected behavior**
System throws exception: Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'SEQUENCE loader: Repeating do not supported now.'
![image](https://github.com/epam/Indigo/assets/26869421/12bb0b8a-a969-463a-91d6-7781e5cf36e9)

**Versions**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
- Indigo Toolkit Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/Indigo/issues/1188

**Comment by AliaksandrDziarkach** [comment] 2024-07-09 08:13
This is duplicate of #2062

**Closed by AliaksandrDziarkach** 2024-07-09 08:13 UTC
Labels: Bug, Priority: Low, HELM
