### ISSUE TITLE
Indigo.calculate method should present 7 digits for precision

### ISSUE THREAD

**Issue by TomasLight** [epam/Indigo#296] opened 2021-01-15 08:01 UTC
Caused by epam/ketcher#212

There is need to present 7 valueable digits for floating values.

Try calculate values for atoms:
Cl, Br, N

Expected result
```
{
  gross: "Br Cl H5 N"
  mass-composition: "H 3.75 Br 59.45 Cl 26.38 N 10.42"
  molecular-weight: 134.4031234
  monoisotopic-mass: 132.9291234
  most-abundant-mass: 132.9291234
}
```

Actual result
```
{
  gross: "Br Cl H5 N"
  mass-composition: "H 3.75 Br 59.45 Cl 26.38 N 10.42"
  molecular-weight: 134.403
  monoisotopic-mass: 132.929
  most-abundant-mass: 132.929
}
```

**Comment by mkviatkovskii** [comment] 2021-01-22 10:20
@TomasLight Could you please specify what component causes the issue - Indigo REST Service or indigo-wasm (for standalone Ketcher)?

**Comment by TomasLight** [comment] 2021-01-22 18:07
@mkviatkovskii indigo-wasm

**Comment by SunFellow** [comment] 2021-01-23 01:15
The root cause has been found and will be fixed at wasm-indigo side.

**Comment by even1024** [comment] 2021-02-20 21:46
fixed in PR: fix296
![precision](https://user-images.githubusercontent.com/7814977/108609311-283dba00-73de-11eb-9387-773c662f7d28.png)

**Closed** 2021-03-03 10:30 UTC
Labels: Bug, Indigo API, Low priority
