### ISSUE TITLE
Indigo.check method returns incorrect errors (or doesn't return when it should)

### ISSUE THREAD

**Issue by TomasLight** [epam/Indigo#293] opened 2021-01-14 07:15 UTC
Caused by epam/ketcher#211

**first argument**
file `All atom properties.mol`
<details>
  <summary>file content</summary>

  ```

  SMMXDraw04061618152D

 27 26  2  0  0  0  0  0  0  0999 V2000
    6.5709   -4.1572    0.0000 N   0  3  0  0  0  4  0  0  0  0  0  0
    7.3070   -3.7322    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.0432   -4.1572    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.7793   -3.7322    0.0000 Q   0  0  0  0  0  0  0  0  0  0  0  0
    9.5154   -4.1572    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
   10.2515   -3.7322    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.9877   -4.1572    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.7238   -3.7322    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.4599   -4.1572    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.1960   -3.7322    0.0000 C   0  0  3  1  0  0  1  0  0  0  0  0
   13.9321   -4.1572    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.6683   -3.7322    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.4044   -4.1572    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.1405   -3.7322    0.0000 C   0  0  3  0  0  0  0  0  0  0  0  0
   16.8766   -4.1572    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.6128   -3.7322    0.0000 C   0  0  3  0  0  0  0  0  0  0  0  0
   18.3489   -4.1572    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   19.0850   -3.7322    0.0000 C   0  4  0  0  0  0  0  0  0  0  0  0
    9.5154   -5.0072    0.0000 C   0  0  3  0  0  0  0  0  0  0  0  0
    8.7793   -5.4322    0.0000 L   0  0  0  0  0  0  0  0  0  0  0  0
   10.2515   -5.4322    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.2515   -6.2822    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.9877   -6.7072    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.9877   -7.5572    0.0000 C   1  0  0  0  0  0  0  0  0  0  0  0
   11.7238   -7.9822    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.7238   -8.8322    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.4599   -9.2572    0.0000 L   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  1  0  0  0  0
  4  5  1  0  0  0  0
  5  6  1  0  0  0  0
  6  7  1  0  0  0  0
  7  8  1  0  0  0  0
  8  9  1  0  0  0  0
  9 10  1  0  0  0  0
 10 11  1  0  0  0  0
 11 12  1  0  0  0  0
 12 13  1  0  0  0  0
 13 14  1  0  0  0  0
 14 15  1  0  0  0  0
 15 16  1  0  0  0  0
 16 17  1  0  0  0  0
 17 18  1  0  0  0  0
  5 19  1  0  0  0  0
 19 20  1  0  0  0  0
 19 21  1  0  0  0  0
 21 22  1  0  0  0  0
 22 23  1  0  0  0  0
 23 24  1  0  0  0  0
 24 25  1  0  0  0  0
 25 26  1  0  0  0  0
 26 27  1  0  0  0  0
 20 F    5   6   7   8   9  17
 27 T    5   6   7   5  13  31
M  CHG  1   1   1
M  RAD  3  14   3  16   1  18   2
M  ISO  1  24  13
M  RBC  4   6  -1  21   4  23   3  25   2
M  SUB  1  12   2
M  UNS  1   8   1
M  ALS  20  7 F C   N   O   F   Cl  Br  I   
M  ALS  27  5 T C   N   B   Al  Ga  
M  END

  ```
</details>

**second argument**
`"radicals;pseudoatoms;stereo;query;overlapping_atoms;overlapping_bonds;rgroups;chiral;3d"`

**third argument**
```
{ rb: {"ub":{"name":"map<string, string>*","tb":{"name":"map<string, string>","Eb":{},"Jb":0,"hc":0,"rc":[],"Bb":[null]},"Vb":false,"Nb":false,"Ob":false,"Ab":null},"sb":5783384,"count":{"value":1}}}
```

**Expected follow error messages:**
"Query warning: Structure contains query features"
"Radical warning: Structure contains 3 atoms with radical electrons"
"Stereochemistry warning: Structure has stereochemistry errors"

**Actual received messages:**
"warning: Structure contains radicals"

**Comment by TomasLight** [comment] 2021-01-14 07:41
probably issue is in WASM code

**Comment by mkviatkovskii** [comment] 2021-01-22 12:30
@TomasLight, could you please attach the molfile instead of providing a text? Molfile heavily depends on formatting (spaces, tabs, etc) - and your data could not be opened (even in Ketcher).

**Comment by TomasLight** [comment] 2021-01-22 14:18
@mkviatkovskii 
[All atom properties.zip](https://github.com/epam/Indigo/files/5856379/All.atom.properties.zip)

**Comment by Dmitrii-Chernov-epam-com** [comment] 2021-01-22 17:59
Fixed in the #269 

The response:
[{"code":6,"message":"Structure contains radicals","ids":[13,15,17]},{"code":14,"message":"Structure contains query features"}]

The message "Stereochemistry warning: Structure has stereochemistry errors" was a bug: "stereo" check is not applicable to QueryMolecule. This message was caused by exception on attempt to use QueryMolecule as Molecule.

**Comment by KseniiaSemenishcheva** [comment] 2021-02-11 12:54
It's important to add following warnings too(which are not mentioned here):
'R-Groups warning:Structure contains RGroup components'
'Chirality warning: Structure has Chiral flag'
'Pseudoatoms warning: Structure contains Pseudoatoms'

**Comment by Dmitrii-Chernov-epam-com** [comment] 2021-02-11 13:07
@KseniiaSemenishcheva , please, attach a molfile which shall produce these warnings

**Comment by KseniiaSemenishcheva** [comment] 2021-02-11 13:34
@Dmitrii-Chernov-epam-com 
[Warnings.zip](https://github.com/epam/Indigo/files/5965564/Warnings.zip)

**Comment by Dmitrii-Chernov-epam-com** [comment] 2021-02-15 06:38
@KseniiaSemenishcheva, all the cases in Warnings.zip are already implemented and tests are successful:
![image](https://user-images.githubusercontent.com/76469602/107913416-75023a80-6f71-11eb-8e7f-bc48a8af318d.png)

What is the problem?

**Comment by KseniiaSemenishcheva** [comment] 2021-02-16 12:49
@Dmitrii-Chernov-epam-com In Ketcher Standalone mode incorrect warnings still reproduce, we are waiting for new version of Indigo module to check actual result.
My comment is only kind reminder because in original issue only 3 types of warnings are mentioned.

**Comment by Dmitrii-Chernov-epam-com** [comment] 2021-02-17 07:32
@KseniiaSemenishcheva , this is the next step.
Currently nothing changed in Ketcher. It still using old version.
Ketcher should be refactored to 
a) switch to new endpoint "check2"
b) interpret JSON response messages instead of plain text.

Only after that the testing performed by you will be related to this PR.

**Comment by AlexanderSavelyev** [comment] 2021-02-19 15:20
@Dmitrii-Chernov-epam-com  expected format is 

{
  "query": "Structure contains query features", 
  "radicals": "Structure contains 3 atoms with radical electrons", 
  "stereo": "Structure has stereochemistry errors"
}

**Comment by even1024** [comment] 2021-02-22 17:14
Added conversion to required format

**Comment by AndreiMazol** [comment] 2021-03-24 15:38
Issue is still reproduced.

**Comment by SunFellow** [comment] 2021-03-24 20:07
@mkviatkovskii , @AndreiMazol, how did you agree about using new cheker2? Replace, keeping the same API name, or provide both names and switch clients to checker2?

**Closed** 2021-03-26 15:17 UTC
Labels: Bug, High priority, Indigo API
