### ISSUE TITLE
HELM ver. 2.04  support one sequence import and export

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#1186] opened 2023-07-19 11:20 UTC
**Background**
Indigo macromolecules support
This ticket covers only sequence (no connections table  )

**Solution**
Implement import and export of one RNA or PEPRIDE or CHEM, support inline SMILES.
Tests should include corresponding KET<>HELM conversions.

HELM notation could be found here: https://www.pistoiaalliance.org/helm-notation/
Reference: [HELM Specification 2_04.pdf](https://github.com/user-attachments/files/15740995/HELM.Specification.2_04.pdf)
Decided to support only features that implemented in Ketcher already

**Comment by AlexeyGirin** [comment] 2024-06-14 10:11
Duplicate of https://github.com/epam/Indigo/issues/1188

**Closed by AlexeyGirin** 2024-06-14 10:11 UTC
Labels: epic: macromolecules, Test Cases Written
