### ISSUE TITLE
SMILES format does not store alias information

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1124] opened 2023-05-03 08:47 UTC
**Steps to Reproduce**
1. Open Ketcher
2. Add file [alias-pseudoatom.zip](https://github.com/epam/Indigo/files/11380809/alias-pseudoatom.zip) on canvas
3. Save it in Daylight SMILES format
4. Open saved file

Note: Extended SMILES format does not store alias information as well

**Expected behavior**
Alias is present on structure
![2023-05-03_11h37_37](https://user-images.githubusercontent.com/62464241/235868964-6e2e1781-d7ff-48ce-a018-8f6db54245f7.png)

**Actual behavior**
Alias is absent on structure
![2023-05-03_11h37_20](https://user-images.githubusercontent.com/62464241/235868984-76cb8580-2b2f-4671-bbb1-2572c3ba60fa.png)

**Indigo/Bingo version**  
Version 1.11.0-rc.1.0-g0dec096b8-x86_64-linux-gnu-11.2.1

**Comment by mkviatkovskii** [comment] 2023-05-26 09:45
Duplicate of #884

**Closed by mkviatkovskii** 2023-05-26 09:45 UTC
Labels: Bug
