### ISSUE TITLE
Preview: Save of unknown monomer to IDT doesn't work

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2043] opened 2024-07-01 09:08 UTC
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type: `/i2AmPr/`
![image](https://github.com/epam/ketcher/assets/26869421/fbc222f8-0ed5-450b-8db7-8e11418896d5)
![image](https://github.com/epam/Indigo/assets/26869421/c30393b4-11e9-4d3d-b8cb-f0aa9aab974f)
3. Save canvas to IDT

**Actual behavior**
System throws exception: Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'molecule json loader: Expected atoms block not found', 'RXN loader: bad header {', 'RXN loader: bad header {', 'molecule json loader: Expected atoms block not found'
![image](https://github.com/epam/Indigo/assets/26869421/e4383fbc-42c0-414d-b3ca-81a5642d76a6)

**Expected behavior**
System saves canvas as `/i2AmPr/`
![image](https://github.com/epam/Indigo/assets/26869421/f7bbffe5-3cf9-4341-867c-167cd4f02fc9)

As per [requirements](https://github.com/epam/ketcher/issues/4431):
```
There should be possible to load such monomers from IDT and KET formats and save to these formats.
```

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4431

**Comment by Zhirnoff** [comment] 2024-07-01 09:15
Also we can import multiple sequences but can not export it. Same error like in bug.
![2024-07-01_12h14_19](https://github.com/epam/Indigo/assets/62464241/99f6f2c1-a37f-42ed-8ed6-bcca58fe6bc9)

**Comment by even1024** [comment] 2024-07-02 12:53
Change default error message in case of unknown format

**Comment by AliaksandrDziarkach** [comment] 2024-07-04 10:47
This is duplicate of #2044

**Closed by AliaksandrDziarkach** 2024-07-04 10:47 UTC
Labels: Bug, Priority: High, IDT

**Comment by AnnaKosol** [comment] 2024-07-12 07:44
Tested, ok with one monomer and multiple sequences
![Image](https://github.com/user-attachments/assets/755efe83-6886-4e2b-8d6f-21c8d054b0b7)

**Versions:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
